### ISSUE TITLE
TypeError: Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by RamiYahyaRY** [anishkny/integrify#22]
I get this error:

```
TypeError: Cannot read property 'collection' of undefined
    at /srv/node_modules/integrify/lib/rules/replicateAttributes.js:61:18
    at Array.forEach (<anonymous>)
    at /srv/node_modules/integrify/lib/rules/replicateAttributes.js:47:22
    at cloudFunctionNewSignature (/srv/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
    at /worker/worker.js:825:24
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

I have the following Firebase Cloud Function running in Node 8 environment with Typescript code:

```javascript

import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
const { integrify } = require('integrify'); 

admin.initializeApp();
const firestore = admin.firestore();
integrify({ config: { functions, firestore } });

exports.inventory_item_replicate = integrify({
    rule: 'REPLICATE_ATTRIBUTES',
    source: {
      collection: 'inventory_item',
    },
    targets: [
      {
        collection: 'cart',
        foreignKey: 'id',
        attributeMapping: { 
            'barcode': 'barcode',
            'category': 'category', 
            'image': 'image', 
            'name': 'name', 
            'price': 'price',
            'stock': 'stock',
            'type': 'type',
        },
      },
    ],
  }); 
```

The replication function seems to fire correctly after an update on the original collection, as I can see from the logs, and the error is logged directly afterwards:

```
integrify: Detected update in [inventory_item], id [QmNKvERKZI3HFEyKz3Ft], 
new value: { ...
...
...
...
integrify: On collection [cart], applying update: { ....
```

**Comment by anishkny** [comment]
Hey @RamiYahyaRY thanks for trying out `integrify`!

Could you edit the configuration line thus:

```
integrify({ config: { functions, db: firestore } });
```

`integrify` expects two keys in the `config` object: `functions` and `db`.

LMK if it works. I can enhance it to throw better error message.

**Comment by RamiYahyaRY** [comment]
@anishkny Thanks a lot. That works.

Is there a way to bind a collection to a subcollection? Consider this:

```
  /users/
    userId/
      username
      photoURL

  /articles/
    articleId/
       comments/
          commentId/
             body
             userId       <-- foreign key
             username     <-- replicated field
             photoURL     <-- replicated field
```

Is there a way to do something like this:

```
{
    rule: 'REPLICATE_ATTRIBUTES',
    source: {
      collection: 'users',
    },
    targets: [
      {
        collection: 'articles/{articleId}/comments',
        foreignKey: 'userId',
        attributeMapping: { 
            ...
        },
      }
   ]
}
```

**Comment by anishkny** [comment]
@RamiYahyaRY currently, there isn't a way to replicate to nested collections (subcollections). Although it is on the roadmap as #9. 

I will leave this issue open to throw better error messages in case of incorrect config (your original issue).

**Comment by anishkny** [comment]
@RamiYahyaRY you can now replicate to sub-collections using `integrify` thus:

```js
module.exports.replicateMasterToDetail = integrify({
  rule: 'REPLICATE_ATTRIBUTES',
  source: {
    collection: 'master',
  },
  targets: [
    {
      collection: 'subcollection',
      foreignKey: 'masterId',
      attributeMapping: {
        masterField1: 'detail1Field1',
      },
    },
    isCollectionGroup: true,    // <---- NEWLY ADDED!
  ],
```

This was added in [v2.1.0](https://github.com/anishkny/integrify/blob/master/CHANGELOG.md#210-2019-08-09)

**Comment by devth** [comment]
Can the source be a collection group?

**Comment by anishkny** [comment]
@devth lets continue this discussion at #56
